# Generated by Django 3.0.6 on 2020-05-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Actor'),
        ),
        migrations.AlterField(
            model_name='role',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Show'),
        ),
    ]
