# Generated by Django 3.0.6 on 2020-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200509_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='raw_data',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='successful_parse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='url',
            field=models.CharField(db_index=True, default='', max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
