# Generated by Django 3.0.6 on 2020-06-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200610_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='url',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
