# Generated by Django 3.0.6 on 2020-06-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_role_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('index', models.IntegerField(default=0)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metadata', to='base.Show')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
