# Generated by Django 3.0.6 on 2020-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='name',
        ),
        migrations.AddField(
            model_name='metadata',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
