# Generated by Django 4.0.2 on 2022-02-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200620_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='metadata_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foo', to='base.metadataobject'),
        ),
    ]
