# Generated by Django 4.0.2 on 2022-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_metadata_metadata_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(db_collation='NOCASE', db_index=True, max_length=255, unique=True),
        ),
    ]
